/* Generated by re2c 4.5.1 on Wed Jun 10 16:46:25 2026 */
#line 1 "src/c/lexer/lexer.re"
#include "core/types.h"
#include "c/lexer/lexer.h"
#include "c/lexer/token.h"
#include "core/logger/logger.h"
#include <stdio.h>
#include <string.h>

static void
s_update_pos(struct dpp_lexer *lex)
{
    lex->lex_column += (u32)(lex->lex_cursor - lex->lex_token);
}

s32
dpp_lexer_next(struct dpp_lexer *lex)
{
lex_next:
    lex->lex_token = lex->lex_cursor;

/* clang-format off */
    
#line 25 "src/c/lexer/lexer.re.c"
{
	u8 yych;
	unsigned int yyaccept = 0;
	if (lex->lex_limit <= lex->lex_cursor) goto yy442;
	yych = *lex->lex_cursor;
	switch (yych) {
		case '\t':
		case '\v':
		case '\f':
		case ' ': goto yy3;
		case '\n': goto yy5;
		case '\r': goto yy6;
		case '!': goto yy7;
		case '"': goto yy9;
		case '#': goto yy10;
		case '%': goto yy11;
		case '&': goto yy13;
		case '\'': goto yy15;
		case '(': goto yy16;
		case ')': goto yy17;
		case '*': goto yy18;
		case '+': goto yy20;
		case ',': goto yy22;
		case '-': goto yy23;
		case '.': goto yy25;
		case '/': goto yy27;
		case '0': goto yy29;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		case ':': goto yy32;
		case ';': goto yy33;
		case '<': goto yy34;
		case '=': goto yy36;
		case '>': goto yy38;
		case '?': goto yy40;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '[': goto yy44;
		case '\\': goto yy46;
		case ']': goto yy47;
		case '^': goto yy49;
		case '_': goto yy51;
		case 'a': goto yy52;
		case 'b': goto yy53;
		case 'c': goto yy54;
		case 'd': goto yy55;
		case 'e': goto yy56;
		case 'f': goto yy57;
		case 'g': goto yy58;
		case 'i': goto yy59;
		case 'l': goto yy60;
		case 'r': goto yy61;
		case 's': goto yy62;
		case 't': goto yy63;
		case 'u': goto yy64;
		case 'v': goto yy65;
		case 'w': goto yy66;
		case '{': goto yy67;
		case '|': goto yy68;
		case '}': goto yy70;
		case '~': goto yy71;
		default: goto yy1;
	}
yy1:
	++lex->lex_cursor;
yy2:
#line 200 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_EOF; }
#line 136 "src/c/lexer/lexer.re.c"
yy3:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '\t':
		case '\v':
		case '\f':
		case ' ': goto yy3;
		default: goto yy4;
	}
yy4:
#line 40 "src/c/lexer/lexer.re"
	{ lex->lex_column += (u32)(lex->lex_cursor - lex->lex_token); goto lex_next; }
#line 149 "src/c/lexer/lexer.re.c"
yy5:
	++lex->lex_cursor;
#line 47 "src/c/lexer/lexer.re"
	{ 
            lex->lex_line++;
            lex->lex_line_ptr = lex->lex_cursor;
            lex->lex_column = 1;
            lex->lex_is_bol = true;
            goto lex_next;
        }
#line 160 "src/c/lexer/lexer.re.c"
yy6:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '\n': goto yy5;
		default: goto yy2;
	}
yy7:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy72;
		default: goto yy8;
	}
yy8:
#line 169 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_BANG; }
#line 176 "src/c/lexer/lexer.re.c"
yy9:
	yyaccept = 0;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	goto yy74;
yy10:
	++lex->lex_cursor;
#line 55 "src/c/lexer/lexer.re"
	{
            if (lex->lex_is_bol) {
                s_update_pos(lex);
                lex->lex_is_bol = false;
                return TOK_PP_HASH;
            }
            s_update_pos(lex);
            lex->lex_is_bol = false;
            return '#';
        }
#line 194 "src/c/lexer/lexer.re.c"
yy11:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy78;
		default: goto yy12;
	}
yy12:
#line 175 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_MOD; }
#line 204 "src/c/lexer/lexer.re.c"
yy13:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '&': goto yy79;
		case '=': goto yy80;
		default: goto yy14;
	}
yy14:
#line 168 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_AMP; }
#line 215 "src/c/lexer/lexer.re.c"
yy15:
	yyaccept = 0;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	goto yy82;
yy16:
	++lex->lex_cursor;
#line 163 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return '('; }
#line 224 "src/c/lexer/lexer.re.c"
yy17:
	++lex->lex_cursor;
#line 164 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return ')'; }
#line 229 "src/c/lexer/lexer.re.c"
yy18:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy85;
		default: goto yy19;
	}
yy19:
#line 173 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_STAR; }
#line 239 "src/c/lexer/lexer.re.c"
yy20:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '+': goto yy86;
		case '=': goto yy87;
		default: goto yy21;
	}
yy21:
#line 172 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_PLUS; }
#line 250 "src/c/lexer/lexer.re.c"
yy22:
	++lex->lex_cursor;
#line 160 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return ','; }
#line 255 "src/c/lexer/lexer.re.c"
yy23:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '-': goto yy88;
		case '=': goto yy89;
		case '>': goto yy90;
		default: goto yy24;
	}
yy24:
#line 171 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_MINUS; }
#line 267 "src/c/lexer/lexer.re.c"
yy25:
	yyaccept = 1;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	switch (yych) {
		case '.': goto yy91;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		default: goto yy26;
	}
yy26:
#line 167 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DOT; }
#line 288 "src/c/lexer/lexer.re.c"
yy27:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '*': goto yy94;
		case '/': goto yy95;
		case '=': goto yy97;
		default: goto yy28;
	}
yy28:
#line 174 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DIV; }
#line 300 "src/c/lexer/lexer.re.c"
yy29:
	yyaccept = 2;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	switch (yych) {
		case '.': goto yy92;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		case 'F':
		case 'f': goto yy30;
		case 'L':
		case 'l': goto yy100;
		case 'U':
		case 'u': goto yy101;
		case 'X':
		case 'x': goto yy102;
		default: goto yy93;
	}
yy30:
#line 192 "src/c/lexer/lexer.re"
	{ 
            s_update_pos(lex); lex->lex_is_bol = false; return TOK_NUMBER; 
        }
#line 331 "src/c/lexer/lexer.re.c"
yy31:
	yyaccept = 2;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	switch (yych) {
		case '.': goto yy92;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy31;
		case 'D':
		case 'K':
		case 'd':
		case 'k': goto yy98;
		case 'E':
		case 'e': goto yy99;
		case 'L':
		case 'l': goto yy100;
		case 'U':
		case 'u': goto yy101;
		default: goto yy30;
	}
yy32:
	++lex->lex_cursor;
#line 161 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return ':'; }
#line 363 "src/c/lexer/lexer.re.c"
yy33:
	++lex->lex_cursor;
#line 157 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return ';'; }
#line 368 "src/c/lexer/lexer.re.c"
yy34:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '<': goto yy103;
		case '=': goto yy105;
		default: goto yy35;
	}
yy35:
#line 176 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_LT; }
#line 379 "src/c/lexer/lexer.re.c"
yy36:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy106;
		default: goto yy37;
	}
yy37:
#line 162 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return '='; }
#line 389 "src/c/lexer/lexer.re.c"
yy38:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy107;
		case '>': goto yy108;
		default: goto yy39;
	}
yy39:
#line 177 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_GT; }
#line 400 "src/c/lexer/lexer.re.c"
yy40:
	++lex->lex_cursor;
#line 180 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_QUERY; }
#line 405 "src/c/lexer/lexer.re.c"
yy41:
	yych = *++lex->lex_cursor;
yy42:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy43;
	}
yy43:
#line 185 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_IDENT; }
#line 478 "src/c/lexer/lexer.re.c"
yy44:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '[': goto yy110;
		default: goto yy45;
	}
yy45:
#line 165 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return '['; }
#line 488 "src/c/lexer/lexer.re.c"
yy46:
	yyaccept = 0;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	switch (yych) {
		case '\n': goto yy111;
		case '\r': goto yy112;
		default: goto yy2;
	}
yy47:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case ']': goto yy113;
		default: goto yy48;
	}
yy48:
#line 166 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return ']'; }
#line 506 "src/c/lexer/lexer.re.c"
yy49:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy114;
		default: goto yy50;
	}
yy50:
#line 178 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_CARET; }
#line 516 "src/c/lexer/lexer.re.c"
yy51:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'A': goto yy115;
		case 'B': goto yy116;
		case 'C': goto yy117;
		case 'D': goto yy118;
		case 'I': goto yy119;
		case 'U': goto yy120;
		case '_': goto yy121;
		default: goto yy42;
	}
yy52:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy122;
		case 'u': goto yy123;
		default: goto yy42;
	}
yy53:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy124;
		default: goto yy42;
	}
yy54:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy125;
		case 'h': goto yy126;
		case 'o': goto yy127;
		default: goto yy42;
	}
yy55:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy128;
		case 'o': goto yy129;
		default: goto yy42;
	}
yy56:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy131;
		case 'n': goto yy132;
		case 'x': goto yy133;
		default: goto yy42;
	}
yy57:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy134;
		case 'l': goto yy135;
		case 'o': goto yy136;
		default: goto yy42;
	}
yy58:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy137;
		default: goto yy42;
	}
yy59:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'f': goto yy138;
		case 'n': goto yy140;
		default: goto yy42;
	}
yy60:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy141;
		default: goto yy42;
	}
yy61:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy142;
		default: goto yy42;
	}
yy62:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'h': goto yy143;
		case 'i': goto yy144;
		case 't': goto yy145;
		case 'w': goto yy146;
		default: goto yy42;
	}
yy63:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy147;
		case 'y': goto yy148;
		default: goto yy42;
	}
yy64:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy149;
		default: goto yy42;
	}
yy65:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy150;
		default: goto yy42;
	}
yy66:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'h': goto yy151;
		default: goto yy42;
	}
yy67:
	++lex->lex_cursor;
#line 158 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return '{'; }
#line 636 "src/c/lexer/lexer.re.c"
yy68:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy152;
		case '|': goto yy153;
		default: goto yy69;
	}
yy69:
#line 179 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_PIPE; }
#line 647 "src/c/lexer/lexer.re.c"
yy70:
	++lex->lex_cursor;
#line 159 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return '}'; }
#line 652 "src/c/lexer/lexer.re.c"
yy71:
	++lex->lex_cursor;
#line 170 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_TILDE; }
#line 657 "src/c/lexer/lexer.re.c"
yy72:
	++lex->lex_cursor;
#line 156 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_NE; }
#line 662 "src/c/lexer/lexer.re.c"
yy73:
	yych = *++lex->lex_cursor;
yy74:
	switch (yych) {
		case '"': goto yy75;
		case '\\': goto yy76;
		default: goto yy73;
	}
yy75:
	++lex->lex_cursor;
#line 196 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_STRING; }
#line 675 "src/c/lexer/lexer.re.c"
yy76:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '\n': goto yy77;
		default: goto yy73;
	}
yy77:
	lex->lex_cursor = lex->lex_marker;
	switch (yyaccept) {
		case 0: goto yy2;
		case 1: goto yy26;
		default: goto yy30;
	}
yy78:
	++lex->lex_cursor;
#line 142 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_MOD_ASSIGN; }
#line 693 "src/c/lexer/lexer.re.c"
yy79:
	++lex->lex_cursor;
#line 151 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_AND; }
#line 698 "src/c/lexer/lexer.re.c"
yy80:
	++lex->lex_cursor;
#line 143 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_AND_ASSIGN; }
#line 703 "src/c/lexer/lexer.re.c"
yy81:
	yych = *++lex->lex_cursor;
yy82:
	switch (yych) {
		case '\'': goto yy83;
		case '\\': goto yy84;
		default: goto yy81;
	}
yy83:
	++lex->lex_cursor;
#line 197 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_CHAR_LITERAL; }
#line 716 "src/c/lexer/lexer.re.c"
yy84:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '\n': goto yy77;
		default: goto yy81;
	}
yy85:
	++lex->lex_cursor;
#line 140 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_MUL_ASSIGN; }
#line 727 "src/c/lexer/lexer.re.c"
yy86:
	++lex->lex_cursor;
#line 148 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_INC; }
#line 732 "src/c/lexer/lexer.re.c"
yy87:
	++lex->lex_cursor;
#line 138 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ADD_ASSIGN; }
#line 737 "src/c/lexer/lexer.re.c"
yy88:
	++lex->lex_cursor;
#line 149 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DEC; }
#line 742 "src/c/lexer/lexer.re.c"
yy89:
	++lex->lex_cursor;
#line 139 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_SUB_ASSIGN; }
#line 747 "src/c/lexer/lexer.re.c"
yy90:
	++lex->lex_cursor;
#line 150 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ARROW; }
#line 752 "src/c/lexer/lexer.re.c"
yy91:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '.': goto yy154;
		default: goto yy77;
	}
yy92:
	yyaccept = 2;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
yy93:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		case 'D':
		case 'F':
		case 'K':
		case 'L':
		case 'd':
		case 'f':
		case 'k':
		case 'l': goto yy98;
		case 'E':
		case 'e': goto yy99;
		case 'U':
		case 'u': goto yy155;
		default: goto yy30;
	}
yy94:
	++lex->lex_cursor;
#line 67 "src/c/lexer/lexer.re"
	{
            for (;;) {
                if (lex->lex_cursor >= lex->lex_limit) return TOK_EOF;
                if (lex->lex_cursor[0] == '*' && lex->lex_cursor[1] == '/') {
                    lex->lex_cursor += 2;
                    goto lex_next;
                }
                if (*lex->lex_cursor == '\n') {
                    lex->lex_line++;
                    lex->lex_line_ptr = lex->lex_cursor + 1;
                    lex->lex_column = 1;
                    lex->lex_is_bol = true;
                }
                lex->lex_cursor++;
            }
        }
#line 807 "src/c/lexer/lexer.re.c"
yy95:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '\n':
		case '\r': goto yy96;
		default: goto yy95;
	}
yy96:
#line 66 "src/c/lexer/lexer.re"
	{ goto lex_next; }
#line 818 "src/c/lexer/lexer.re.c"
yy97:
	++lex->lex_cursor;
#line 141 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DIV_ASSIGN; }
#line 823 "src/c/lexer/lexer.re.c"
yy98:
	++lex->lex_cursor;
	goto yy30;
yy99:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '+':
		case '-': goto yy156;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy157;
		default: goto yy77;
	}
yy100:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'L':
		case 'l': goto yy158;
		case 'U':
		case 'u': goto yy98;
		default: goto yy30;
	}
yy101:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'K':
		case 'k': goto yy98;
		case 'L':
		case 'l': goto yy159;
		default: goto yy30;
	}
yy102:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '.': goto yy160;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy161;
		default: goto yy77;
	}
yy103:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy162;
		default: goto yy104;
	}
yy104:
#line 147 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_LSHIFT; }
#line 899 "src/c/lexer/lexer.re.c"
yy105:
	++lex->lex_cursor;
#line 153 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_LE; }
#line 904 "src/c/lexer/lexer.re.c"
yy106:
	++lex->lex_cursor;
#line 155 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_EQ; }
#line 909 "src/c/lexer/lexer.re.c"
yy107:
	++lex->lex_cursor;
#line 154 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_GE; }
#line 914 "src/c/lexer/lexer.re.c"
yy108:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '=': goto yy163;
		default: goto yy109;
	}
yy109:
#line 146 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_RSHIFT; }
#line 924 "src/c/lexer/lexer.re.c"
yy110:
	++lex->lex_cursor;
#line 181 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ATTR_OPEN; }
#line 929 "src/c/lexer/lexer.re.c"
yy111:
	++lex->lex_cursor;
#line 41 "src/c/lexer/lexer.re"
	{
            lex->lex_line++;
            lex->lex_column = 1;
            lex->lex_is_bol = true;
            goto lex_next;
        }
#line 939 "src/c/lexer/lexer.re.c"
yy112:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '\n': goto yy111;
		default: goto yy77;
	}
yy113:
	++lex->lex_cursor;
#line 182 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ATTR_CLOSE; }
#line 950 "src/c/lexer/lexer.re.c"
yy114:
	++lex->lex_cursor;
#line 144 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_XOR_ASSIGN; }
#line 955 "src/c/lexer/lexer.re.c"
yy115:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy164;
		default: goto yy42;
	}
yy116:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy165;
		default: goto yy42;
	}
yy117:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy166;
		default: goto yy42;
	}
yy118:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy167;
		default: goto yy42;
	}
yy119:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy168;
		default: goto yy42;
	}
yy120:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'A': goto yy169;
		default: goto yy42;
	}
yy121:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy170;
		case 'b': goto yy171;
		case 'e': goto yy172;
		case 'i': goto yy173;
		case 'r': goto yy174;
		case 's': goto yy175;
		case 't': goto yy176;
		case 'v': goto yy177;
		default: goto yy42;
	}
yy122:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy178;
		default: goto yy42;
	}
yy123:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy180;
		default: goto yy42;
	}
yy124:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy181;
		default: goto yy42;
	}
yy125:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy182;
		default: goto yy42;
	}
yy126:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy183;
		default: goto yy42;
	}
yy127:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy184;
		default: goto yy42;
	}
yy128:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'f': goto yy185;
		default: goto yy42;
	}
yy129:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case 'u': goto yy186;
		default: goto yy130;
	}
yy130:
#line 92 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DO; }
#line 1118 "src/c/lexer/lexer.re.c"
yy131:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy187;
		default: goto yy42;
	}
yy132:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy188;
		default: goto yy42;
	}
yy133:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy189;
		default: goto yy42;
	}
yy134:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy190;
		default: goto yy42;
	}
yy135:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy191;
		default: goto yy42;
	}
yy136:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy192;
		default: goto yy42;
	}
yy137:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy194;
		default: goto yy42;
	}
yy138:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy139;
	}
yy139:
#line 100 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_IF; }
#line 1232 "src/c/lexer/lexer.re.c"
yy140:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy195;
		case 't': goto yy196;
		default: goto yy42;
	}
yy141:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy198;
		default: goto yy42;
	}
yy142:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'g': goto yy199;
		case 's': goto yy200;
		case 't': goto yy201;
		default: goto yy42;
	}
yy143:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy202;
		default: goto yy42;
	}
yy144:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'g': goto yy203;
		case 'z': goto yy204;
		default: goto yy42;
	}
yy145:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy205;
		case 'r': goto yy206;
		default: goto yy42;
	}
yy146:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy207;
		default: goto yy42;
	}
yy147:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy208;
		default: goto yy42;
	}
yy148:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'p': goto yy209;
		default: goto yy42;
	}
yy149:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy210;
		case 's': goto yy211;
		default: goto yy42;
	}
yy150:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy212;
		case 'l': goto yy213;
		default: goto yy42;
	}
yy151:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy214;
		default: goto yy42;
	}
yy152:
	++lex->lex_cursor;
#line 145 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_OR_ASSIGN; }
#line 1316 "src/c/lexer/lexer.re.c"
yy153:
	++lex->lex_cursor;
#line 152 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_OR; }
#line 1321 "src/c/lexer/lexer.re.c"
yy154:
	++lex->lex_cursor;
#line 135 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ELLIPSIS; }
#line 1326 "src/c/lexer/lexer.re.c"
yy155:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'K':
		case 'k': goto yy98;
		default: goto yy77;
	}
yy156:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy157;
		default: goto yy77;
	}
yy157:
	yyaccept = 2;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy157;
		case 'D':
		case 'F':
		case 'K':
		case 'L':
		case 'd':
		case 'f':
		case 'k':
		case 'l': goto yy98;
		case 'U':
		case 'u': goto yy155;
		default: goto yy30;
	}
yy158:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'U':
		case 'u': goto yy98;
		default: goto yy30;
	}
yy159:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'L':
		case 'l': goto yy98;
		default: goto yy30;
	}
yy160:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'P':
		case 'p': goto yy77;
		default: goto yy216;
	}
yy161:
	yyaccept = 2;
	yych = *(lex->lex_marker = ++lex->lex_cursor);
	switch (yych) {
		case '.': goto yy215;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy161;
		case 'K':
		case 'k': goto yy98;
		case 'L':
		case 'l': goto yy100;
		case 'P':
		case 'p': goto yy99;
		case 'U':
		case 'u': goto yy101;
		default: goto yy30;
	}
yy162:
	++lex->lex_cursor;
#line 137 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_LSHIFT_ASSIGN; }
#line 1437 "src/c/lexer/lexer.re.c"
yy163:
	++lex->lex_cursor;
#line 136 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_RSHIFT_ASSIGN; }
#line 1442 "src/c/lexer/lexer.re.c"
yy164:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy217;
		default: goto yy42;
	}
yy165:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy218;
		default: goto yy42;
	}
yy166:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy219;
		default: goto yy42;
	}
yy167:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy220;
		default: goto yy42;
	}
yy168:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy221;
		default: goto yy42;
	}
yy169:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy222;
		default: goto yy42;
	}
yy170:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy223;
		case 't': goto yy224;
		default: goto yy42;
	}
yy171:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy225;
		default: goto yy42;
	}
yy172:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'x': goto yy226;
		default: goto yy42;
	}
yy173:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy227;
		default: goto yy42;
	}
yy174:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy228;
		default: goto yy42;
	}
yy175:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy229;
		default: goto yy42;
	}
yy176:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'y': goto yy230;
		default: goto yy42;
	}
yy177:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy231;
		default: goto yy42;
	}
yy178:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy179;
	}
yy179:
#line 124 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ASM; }
#line 1599 "src/c/lexer/lexer.re.c"
yy180:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy232;
		default: goto yy42;
	}
yy181:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy234;
		default: goto yy42;
	}
yy182:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy235;
		default: goto yy42;
	}
yy183:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy237;
		default: goto yy42;
	}
yy184:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy239;
		case 't': goto yy240;
		default: goto yy42;
	}
yy185:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy241;
		default: goto yy42;
	}
yy186:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'b': goto yy242;
		default: goto yy42;
	}
yy187:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy243;
		default: goto yy42;
	}
yy188:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy245;
		default: goto yy42;
	}
yy189:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy247;
		default: goto yy42;
	}
yy190:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy248;
		default: goto yy42;
	}
yy191:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy249;
		default: goto yy42;
	}
yy192:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy193;
	}
yy193:
#line 98 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_FOR; }
#line 1744 "src/c/lexer/lexer.re.c"
yy194:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy250;
		default: goto yy42;
	}
yy195:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy252;
		default: goto yy42;
	}
yy196:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy197;
	}
yy197:
#line 102 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_INT; }
#line 1828 "src/c/lexer/lexer.re.c"
yy198:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'g': goto yy253;
		default: goto yy42;
	}
yy199:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy255;
		default: goto yy42;
	}
yy200:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy256;
		default: goto yy42;
	}
yy201:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy257;
		default: goto yy42;
	}
yy202:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy258;
		default: goto yy42;
	}
yy203:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy259;
		default: goto yy42;
	}
yy204:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy260;
		default: goto yy42;
	}
yy205:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy261;
		default: goto yy42;
	}
yy206:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy262;
		default: goto yy42;
	}
yy207:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy263;
		default: goto yy42;
	}
yy208:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy264;
		default: goto yy42;
	}
yy209:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy266;
		default: goto yy42;
	}
yy210:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy267;
		default: goto yy42;
	}
yy211:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy268;
		default: goto yy42;
	}
yy212:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'd': goto yy269;
		default: goto yy42;
	}
yy213:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy271;
		default: goto yy42;
	}
yy214:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy272;
		default: goto yy42;
	}
yy215:
	yych = *++lex->lex_cursor;
yy216:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy215;
		case 'P':
		case 'p': goto yy99;
		default: goto yy77;
	}
yy217:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy273;
		default: goto yy42;
	}
yy218:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy274;
		default: goto yy42;
	}
yy219:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'p': goto yy276;
		default: goto yy42;
	}
yy220:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy277;
		default: goto yy42;
	}
yy221:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'g': goto yy278;
		default: goto yy42;
	}
yy222:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy279;
		default: goto yy42;
	}
yy223:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy280;
		default: goto yy42;
	}
yy224:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy281;
		default: goto yy42;
	}
yy225:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy282;
		default: goto yy42;
	}
yy226:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy283;
		default: goto yy42;
	}
yy227:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy284;
		default: goto yy42;
	}
yy228:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy285;
		default: goto yy42;
	}
yy229:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'g': goto yy286;
		default: goto yy42;
	}
yy230:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'p': goto yy287;
		default: goto yy42;
	}
yy231:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy288;
		default: goto yy42;
	}
yy232:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy233;
	}
yy233:
#line 85 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_AUTO; }
#line 2122 "src/c/lexer/lexer.re.c"
yy234:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'k': goto yy289;
		default: goto yy42;
	}
yy235:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy236;
	}
yy236:
#line 87 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_CASE; }
#line 2200 "src/c/lexer/lexer.re.c"
yy237:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy238;
	}
yy238:
#line 88 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_CHAR; }
#line 2272 "src/c/lexer/lexer.re.c"
yy239:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy291;
		default: goto yy42;
	}
yy240:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy293;
		default: goto yy42;
	}
yy241:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy294;
		default: goto yy42;
	}
yy242:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy295;
		default: goto yy42;
	}
yy243:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy244;
	}
yy244:
#line 94 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ELSE; }
#line 2368 "src/c/lexer/lexer.re.c"
yy245:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy246;
	}
yy246:
#line 95 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ENUM; }
#line 2440 "src/c/lexer/lexer.re.c"
yy247:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy296;
		default: goto yy42;
	}
yy248:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy297;
		default: goto yy42;
	}
yy249:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy299;
		default: goto yy42;
	}
yy250:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy251;
	}
yy251:
#line 99 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_GOTO; }
#line 2530 "src/c/lexer/lexer.re.c"
yy252:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy301;
		default: goto yy42;
	}
yy253:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy254;
	}
yy254:
#line 103 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_LONG; }
#line 2608 "src/c/lexer/lexer.re.c"
yy255:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy302;
		default: goto yy42;
	}
yy256:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy303;
		default: goto yy42;
	}
yy257:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy304;
		default: goto yy42;
	}
yy258:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy305;
		default: goto yy42;
	}
yy259:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy307;
		default: goto yy42;
	}
yy260:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy308;
		default: goto yy42;
	}
yy261:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy309;
		default: goto yy42;
	}
yy262:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy310;
		default: goto yy42;
	}
yy263:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy311;
		default: goto yy42;
	}
yy264:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy265;
	}
yy265:
#line 119 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_TRUE; }
#line 2734 "src/c/lexer/lexer.re.c"
yy266:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'd': goto yy312;
		case 'o': goto yy313;
		default: goto yy42;
	}
yy267:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy314;
		default: goto yy42;
	}
yy268:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'g': goto yy316;
		default: goto yy42;
	}
yy269:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy270;
	}
yy270:
#line 116 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_VOID; }
#line 2825 "src/c/lexer/lexer.re.c"
yy271:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy317;
		default: goto yy42;
	}
yy272:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy318;
		default: goto yy42;
	}
yy273:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy320;
		default: goto yy42;
	}
yy274:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy275;
	}
yy275:
#line 121 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_BOOL; }
#line 2915 "src/c/lexer/lexer.re.c"
yy276:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy322;
		default: goto yy42;
	}
yy277:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy323;
		default: goto yy42;
	}
yy278:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy324;
		default: goto yy42;
	}
yy279:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy325;
		default: goto yy42;
	}
yy280:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '_': goto yy326;
		default: goto yy179;
	}
yy281:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy327;
		default: goto yy42;
	}
yy282:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy328;
		default: goto yy42;
	}
yy283:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy329;
		default: goto yy42;
	}
yy284:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy330;
		default: goto yy42;
	}
yy285:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy331;
		default: goto yy42;
	}
yy286:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy332;
		default: goto yy42;
	}
yy287:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy333;
		default: goto yy42;
	}
yy288:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy334;
		default: goto yy42;
	}
yy289:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy290;
	}
yy290:
#line 86 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_BREAK; }
#line 3127 "src/c/lexer/lexer.re.c"
yy291:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy292;
	}
yy292:
#line 89 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_CONST; }
#line 3199 "src/c/lexer/lexer.re.c"
yy293:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy335;
		default: goto yy42;
	}
yy294:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy336;
		default: goto yy42;
	}
yy295:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy337;
		default: goto yy42;
	}
yy296:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy339;
		default: goto yy42;
	}
yy297:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy298;
	}
yy298:
#line 120 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_FALSE; }
#line 3295 "src/c/lexer/lexer.re.c"
yy299:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy300;
	}
yy300:
#line 97 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_FLOAT; }
#line 3367 "src/c/lexer/lexer.re.c"
yy301:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy341;
		default: goto yy42;
	}
yy302:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy343;
		default: goto yy42;
	}
yy303:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy344;
		default: goto yy42;
	}
yy304:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy345;
		default: goto yy42;
	}
yy305:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy306;
	}
yy306:
#line 107 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_SHORT; }
#line 3463 "src/c/lexer/lexer.re.c"
yy307:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'd': goto yy347;
		default: goto yy42;
	}
yy308:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'f': goto yy349;
		default: goto yy42;
	}
yy309:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy351;
		default: goto yy42;
	}
yy310:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy353;
		default: goto yy42;
	}
yy311:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'h': goto yy355;
		default: goto yy42;
	}
yy312:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy357;
		default: goto yy42;
	}
yy313:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'f': goto yy358;
		default: goto yy42;
	}
yy314:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy315;
	}
yy315:
#line 114 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_UNION; }
#line 3577 "src/c/lexer/lexer.re.c"
yy316:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy360;
		default: goto yy42;
	}
yy317:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy361;
		default: goto yy42;
	}
yy318:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy319;
	}
yy319:
#line 118 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_WHILE; }
#line 3661 "src/c/lexer/lexer.re.c"
yy320:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy321;
	}
yy321:
#line 130 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ACCUM; }
#line 3733 "src/c/lexer/lexer.re.c"
yy322:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy362;
		default: goto yy42;
	}
yy323:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy363;
		default: goto yy42;
	}
yy324:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy364;
		default: goto yy42;
	}
yy325:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'm': goto yy365;
		default: goto yy42;
	}
yy326:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy178;
		default: goto yy42;
	}
yy327:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy367;
		default: goto yy42;
	}
yy328:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy368;
		default: goto yy42;
	}
yy329:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy369;
		default: goto yy42;
	}
yy330:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy370;
		default: goto yy42;
	}
yy331:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy371;
		default: goto yy42;
	}
yy332:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy372;
		default: goto yy42;
	}
yy333:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy373;
		default: goto yy42;
	}
yy334:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy374;
		default: goto yy42;
	}
yy335:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy375;
		default: goto yy42;
	}
yy336:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy376;
		default: goto yy42;
	}
yy337:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy338;
	}
yy338:
#line 93 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DOUBLE; }
#line 3895 "src/c/lexer/lexer.re.c"
yy339:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy340;
	}
yy340:
#line 96 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_EXTERN; }
#line 3967 "src/c/lexer/lexer.re.c"
yy341:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy342;
	}
yy342:
#line 101 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_INLINE; }
#line 4039 "src/c/lexer/lexer.re.c"
yy343:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy378;
		default: goto yy42;
	}
yy344:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy379;
		default: goto yy42;
	}
yy345:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy346;
	}
yy346:
#line 106 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_RETURN; }
#line 4123 "src/c/lexer/lexer.re.c"
yy347:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy348;
	}
yy348:
#line 108 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_SIGNED; }
#line 4195 "src/c/lexer/lexer.re.c"
yy349:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy350;
	}
yy350:
#line 109 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_SIZEOF; }
#line 4267 "src/c/lexer/lexer.re.c"
yy351:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy352;
	}
yy352:
#line 110 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_STATIC; }
#line 4339 "src/c/lexer/lexer.re.c"
yy353:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy354;
	}
yy354:
#line 111 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_STRUCT; }
#line 4411 "src/c/lexer/lexer.re.c"
yy355:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy356;
	}
yy356:
#line 112 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_SWITCH; }
#line 4483 "src/c/lexer/lexer.re.c"
yy357:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'f': goto yy380;
		default: goto yy42;
	}
yy358:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy359;
	}
yy359:
#line 125 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_TYPEOF; }
#line 4561 "src/c/lexer/lexer.re.c"
yy360:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy382;
		default: goto yy42;
	}
yy361:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy383;
		default: goto yy42;
	}
yy362:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'x': goto yy384;
		default: goto yy42;
	}
yy363:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy386;
		default: goto yy42;
	}
yy364:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy387;
		default: goto yy42;
	}
yy365:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy366;
	}
yy366:
#line 131 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_UACCUM; }
#line 4663 "src/c/lexer/lexer.re.c"
yy367:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'b': goto yy388;
		default: goto yy42;
	}
yy368:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy389;
		default: goto yy42;
	}
yy369:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy390;
		default: goto yy42;
	}
yy370:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy391;
		default: goto yy42;
	}
yy371:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy392;
		default: goto yy42;
	}
yy372:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'd': goto yy393;
		default: goto yy42;
	}
yy373:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'f': goto yy394;
		default: goto yy42;
	}
yy374:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy395;
		default: goto yy42;
	}
yy375:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy396;
		default: goto yy42;
	}
yy376:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy377;
	}
yy377:
#line 91 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DEFAULT; }
#line 4789 "src/c/lexer/lexer.re.c"
yy378:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy398;
		default: goto yy42;
	}
yy379:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy400;
		default: goto yy42;
	}
yy380:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy381;
	}
yy381:
#line 113 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_TYPEDEF; }
#line 4873 "src/c/lexer/lexer.re.c"
yy382:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'd': goto yy402;
		default: goto yy42;
	}
yy383:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy404;
		default: goto yy42;
	}
yy384:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy385;
	}
yy385:
#line 122 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_COMPLEX; }
#line 4957 "src/c/lexer/lexer.re.c"
yy386:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy406;
		default: goto yy42;
	}
yy387:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'r': goto yy408;
		default: goto yy42;
	}
yy388:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'u': goto yy409;
		default: goto yy42;
	}
yy389:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy410;
		default: goto yy42;
	}
yy390:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy411;
		default: goto yy42;
	}
yy391:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '_': goto yy412;
		default: goto yy342;
	}
yy392:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'c': goto yy413;
		default: goto yy42;
	}
yy393:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '_': goto yy414;
		default: goto yy348;
	}
yy394:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy415;
		default: goto yy42;
	}
yy395:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy416;
		default: goto yy42;
	}
yy396:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy397;
	}
yy397:
#line 90 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_CONTINUE; }
#line 5222 "src/c/lexer/lexer.re.c"
yy398:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy399;
	}
yy399:
#line 104 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_REGISTER; }
#line 5294 "src/c/lexer/lexer.re.c"
yy400:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy401;
	}
yy401:
#line 105 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_RESTRICT; }
#line 5366 "src/c/lexer/lexer.re.c"
yy402:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy403;
	}
yy403:
#line 115 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_UNSIGNED; }
#line 5438 "src/c/lexer/lexer.re.c"
yy404:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy405;
	}
yy405:
#line 117 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_VOLATILE; }
#line 5510 "src/c/lexer/lexer.re.c"
yy406:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy406;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy407;
	}
yy407:
#line 132 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_DECIMAL_TYPE; }
#line 5582 "src/c/lexer/lexer.re.c"
yy408:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'y': goto yy417;
		default: goto yy42;
	}
yy409:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy419;
		default: goto yy42;
	}
yy410:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy420;
		default: goto yy42;
	}
yy411:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'o': goto yy421;
		default: goto yy42;
	}
yy412:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy341;
		default: goto yy42;
	}
yy413:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy422;
		default: goto yy42;
	}
yy414:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy347;
		default: goto yy42;
	}
yy415:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy358;
		default: goto yy42;
	}
yy416:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy423;
		default: goto yy42;
	}
yy417:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy418;
	}
yy418:
#line 123 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_IMAGINARY; }
#line 5708 "src/c/lexer/lexer.re.c"
yy419:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'e': goto yy424;
		default: goto yy42;
	}
yy420:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'v': goto yy426;
		default: goto yy42;
	}
yy421:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'n': goto yy427;
		default: goto yy42;
	}
yy422:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '_': goto yy428;
		default: goto yy401;
	}
yy423:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '_': goto yy429;
		default: goto yy405;
	}
yy424:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		case '_': goto yy430;
		default: goto yy425;
	}
yy425:
#line 126 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_ATTRIBUTE; }
#line 5934 "src/c/lexer/lexer.re.c"
yy426:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'a': goto yy431;
		default: goto yy42;
	}
yy427:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy432;
		default: goto yy42;
	}
yy428:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy400;
		default: goto yy42;
	}
yy429:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy404;
		default: goto yy42;
	}
yy430:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy433;
		default: goto yy42;
	}
yy431:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy434;
		default: goto yy42;
	}
yy432:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '_': goto yy435;
		default: goto yy42;
	}
yy433:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy425;
	}
yy434:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'l': goto yy437;
		default: goto yy42;
	}
yy435:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy436;
	}
yy436:
#line 128 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); goto lex_next; }
#line 6122 "src/c/lexer/lexer.re.c"
yy437:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 'i': goto yy438;
		default: goto yy42;
	}
yy438:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 's': goto yy439;
		default: goto yy42;
	}
yy439:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case 't': goto yy440;
		default: goto yy42;
	}
yy440:
	yych = *++lex->lex_cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy41;
		default: goto yy441;
	}
yy441:
#line 127 "src/c/lexer/lexer.re"
	{ s_update_pos(lex); lex->lex_is_bol = false; return TOK_BUILTIN_VA_LIST; }
#line 6212 "src/c/lexer/lexer.re.c"
yy442:
#line 199 "src/c/lexer/lexer.re"
	{ return TOK_EOF; }
#line 6216 "src/c/lexer/lexer.re.c"
}
#line 201 "src/c/lexer/lexer.re"

}
